spring.application.name=email-writer
server.port=${PORT:8080}

# Gemini API configuration
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
gemini.api.key=${GEMINI_API_KEY}

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
